affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cuda
grid: 10
grid_eps: 1
grid_range:
- -1
- 1
k: 2
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 7
symbolic.funs_name.0:
- - x
  - sin
- - x
  - x^2
- - x
  - x
- - x
  - x
- - x
  - x
symbolic.funs_name.1:
- - exp
  - tanh
  - x
  - x
  - x
symbolic_enabled: true
width:
- - 2
  - 0
- - 5
  - 0
- - 1
  - 0
